//! Wire types for the remote-worker protocol (`/api/worker`).
//!
//! These are shared between the backend API and the `aurcache-worker` binary,
//! so their JSON representation is a stable contract. Keep field names stable.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Worker lifecycle states as stored in the `workers.status` column.
pub struct WorkerStatus;

impl WorkerStatus {
    /// Registered but not yet approved by an admin / enrollment path.
    pub const PENDING: &'static str = "pending";
    /// Approved; the worker's certificate is signed and may claim jobs.
    pub const APPROVED: &'static str = "approved";
    /// Explicitly revoked; the worker is refused at the auth guard.
    pub const REVOKED: &'static str = "revoked";
}

/// Enrollment request a worker sends on first contact (no client cert yet).
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct RegisterRequest {
    pub name: String,
    pub native_arches: Vec<String>,
    #[serde(default)]
    pub emulated_arches: Vec<String>,
    pub version: String,
    /// PEM-encoded certificate signing request generated by the worker.
    pub csr_pem: String,
    /// Optional shared enrollment token (`AURCACHE_ENROLLMENT_TOKEN` on the
    /// worker). When it matches the server's configured token the worker is
    /// auto-approved without an admin click.
    #[serde(default)]
    pub enrollment_token: Option<String>,
    /// Exact pkgbase names this worker is specially provisioned for
    /// (`WORKER_PACKAGES`). Reserves those packages to workers that name them.
    #[serde(default)]
    pub packages: Vec<String>,
    /// Scheduling preference, higher wins (`WORKER_PRIORITY`).
    #[serde(default)]
    pub priority: i32,
    /// Maximum concurrent builds (`WORKER_CONCURRENCY`), so the server can tell
    /// whether this worker still has capacity.
    #[serde(default = "default_concurrency")]
    pub concurrency: u32,
}

/// A worker that does not report its concurrency is assumed to run one build.
fn default_concurrency() -> u32 {
    1
}

/// Enrollment status returned while a worker polls for approval.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct RegisterStatus {
    /// One of [`WorkerStatus`] values.
    pub status: String,
    /// PEM of the CA-signed leaf certificate, present once approved.
    pub signed_cert: Option<String>,
    /// PEM of the CA certificate, present once approved (for the worker to pin).
    pub ca_cert: Option<String>,
}

/// A worker's request to claim a job, advertising the arches it can build so
/// the server can route native vs emulated work.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct ClaimRequest {
    pub native_arches: Vec<String>,
    #[serde(default)]
    pub emulated_arches: Vec<String>,
}

/// Everything a worker needs to build a package without ever contacting the AUR.
///
/// Sources are downloaded separately (`GET /jobs/{id}/source`); this carries the
/// self-contained build configuration.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct JobDescriptor {
    pub build_id: i32,
    pub pkgbase: String,
    /// Target architecture, e.g. `x86_64`, `aarch64`.
    pub arch: String,
    #[serde(default)]
    pub build_flags: Vec<String>,
    /// Rendered `makepkg.conf` for the build.
    pub makepkg_conf: String,
    /// Rendered `pacman.conf` for the build.
    pub pacman_conf: String,
    /// Per-arch mirrorlist content when the server has one for this arch;
    /// `None` means the worker falls back to its image's built-in mirrorlist.
    pub mirrorlist: Option<String>,
    /// `validpgpkeys` the worker must trust before building.
    #[serde(default)]
    pub pgp_keys: Vec<String>,
}

/// Periodic liveness signal. Carries the set of builds the worker is actively
/// running so the server can renew their leases and requeue any it dropped.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct Heartbeat {
    pub active_build_ids: Vec<i32>,
    pub version: String,
}

/// Terminal report for a single build.
///
/// A report with `success == false` (including OOM / non-zero exit) is a
/// deterministic failure and marks the build FAILED without re-enqueue.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct CompleteReport {
    pub success: bool,
    /// Exit code of the build process (e.g. 137 for an OOM kill), when known.
    pub exit_code: Option<i32>,
    /// Human-readable failure reason.
    pub reason: Option<String>,
    /// True when the build stopped because it was canceled.
    #[serde(default)]
    pub canceled: bool,
}

/// Worker's poll response for cancel on a specific job.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct JobStatus {
    pub cancel_requested: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn round_trip<T>(value: &T) -> T
    where
        T: Serialize + for<'de> Deserialize<'de>,
    {
        let json = serde_json::to_string(value).expect("serialize");
        serde_json::from_str(&json).expect("deserialize")
    }

    #[test]
    fn job_descriptor_round_trips() {
        let job = JobDescriptor {
            build_id: 42,
            pkgbase: "hello".into(),
            arch: "x86_64".into(),
            build_flags: vec!["--nocheck".into()],
            makepkg_conf: "PACKAGER=x".into(),
            pacman_conf: "[repo]".into(),
            mirrorlist: Some("Server = https://example/\\$repo".into()),
            pgp_keys: vec!["ABCDEF".into()],
        };
        let back = round_trip(&job);
        assert_eq!(job.build_id, back.build_id);
        assert_eq!(job.pgp_keys, back.pgp_keys);
        assert_eq!(job.mirrorlist, back.mirrorlist);
    }

    #[test]
    fn heartbeat_round_trips() {
        let hb = Heartbeat {
            active_build_ids: vec![1, 2, 3],
            version: "0.1.0".into(),
        };
        assert_eq!(round_trip(&hb).active_build_ids, hb.active_build_ids);
    }

    #[test]
    fn complete_report_defaults_canceled_false() {
        let parsed: CompleteReport =
            serde_json::from_str(r#"{"success":false,"exit_code":137}"#).expect("parse");
        assert!(!parsed.success);
        assert_eq!(parsed.exit_code, Some(137));
        assert!(!parsed.canceled);
    }

    #[test]
    fn claim_request_emulated_defaults_empty() {
        let parsed: ClaimRequest =
            serde_json::from_str(r#"{"native_arches":["x86_64"]}"#).expect("parse");
        assert_eq!(parsed.native_arches, vec!["x86_64".to_string()]);
        assert!(parsed.emulated_arches.is_empty());
    }
}
