[package]
name = "aurcache-builder"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = {workspace = true}
tracing = {workspace = true}
tokio = {workspace = true}
sea-orm = {workspace = true}

aurcache-db = {path = "../aurcache-db"}
aurcache-utils = {path = "../aurcache-utils"}
aurcache-activitylog = {path = "../aurcache-activitylog"}
aurcache-common = {path = "../aurcache-common"}
