//! Entity models, originally generated by sea-orm-codegen and now hand-maintained.

pub use aurcache_common::api::activity::Severity;
use sea_orm::entity::prelude::*;
use sea_orm::strum::IntoEnumIterator;

#[derive(Debug, Clone, Copy, PartialEq, EnumIter, DeriveActiveEnum, Eq)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum ActivityType {
    #[sea_orm(num_value = 0)]
    AddPackage,
    #[sea_orm(num_value = 1)]
    RemovePackage,
    #[sea_orm(num_value = 2)]
    UpdatePackage,
    #[sea_orm(num_value = 3)]
    StartBuild,
    #[sea_orm(num_value = 4)]
    FinishBuild,
    /// The server process started. A deploy, a restart, or a crash loop -- all
    /// three are worth being able to line up against what else happened.
    #[sea_orm(num_value = 5)]
    ServerStart,
    /// A machine asked to join the fleet for the first time.
    #[sea_orm(num_value = 6)]
    WorkerEnroll,
    #[sea_orm(num_value = 7)]
    WorkerApprove,
    #[sea_orm(num_value = 8)]
    WorkerRevoke,
    /// A build produced a package that never reached the repository.
    #[sea_orm(num_value = 9)]
    PublishFailed,
    /// A worker stopped answering and the builds it held were requeued.
    #[sea_orm(num_value = 10)]
    WorkerReaped,
    /// A pass of the version check did not finish, so nothing was found to be
    /// out of date that pass.
    #[sea_orm(num_value = 11)]
    VersionCheckFailed,
    /// A worker refused a value its machine was configured with, and is running
    /// something else.
    #[sea_orm(num_value = 12)]
    WorkerSettingRejected,
}

impl ActivityType {
    /// How much attention an entry of this kind deserves.
    ///
    /// An exhaustive match rather than a default arm: a new kind should not be
    /// able to arrive as `Info` by omission, which is exactly how a failure
    /// would end up filed as news.
    #[must_use]
    pub const fn severity(self) -> Severity {
        match self {
            Self::AddPackage
            | Self::RemovePackage
            | Self::UpdatePackage
            | Self::StartBuild
            | Self::FinishBuild
            | Self::ServerStart
            | Self::WorkerEnroll
            | Self::WorkerApprove
            | Self::WorkerRevoke => Severity::Info,
            Self::WorkerReaped | Self::VersionCheckFailed | Self::WorkerSettingRejected => {
                Severity::Warning
            }
            Self::PublishFailed => Severity::Error,
        }
    }

    /// Every kind at or above `floor`, for a filter that means "this and worse".
    #[must_use]
    pub fn at_least(floor: Severity) -> Vec<Self> {
        Self::iter()
            .filter(|kind| kind.severity() >= floor)
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "activity")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub typ: ActivityType,
    pub data: String, // json object
    pub timestamp: i64,
    pub user: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for crate::activities::ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    /// "This and worse" is what a severity filter means, so the set has to
    /// widen downwards and never drop the level that was asked for.
    #[test]
    fn at_least_includes_everything_from_that_level_up() {
        let errors = ActivityType::at_least(Severity::Error);
        assert!(errors.contains(&ActivityType::PublishFailed));
        assert!(!errors.contains(&ActivityType::WorkerReaped));
        assert!(!errors.contains(&ActivityType::AddPackage));

        let warnings = ActivityType::at_least(Severity::Warning);
        assert!(warnings.contains(&ActivityType::PublishFailed));
        assert!(warnings.contains(&ActivityType::WorkerReaped));
        assert!(!warnings.contains(&ActivityType::AddPackage));

        // Everything, which is the same as no filter at all.
        assert_eq!(
            ActivityType::at_least(Severity::Info).len(),
            ActivityType::iter().count()
        );
    }

    /// Ordinary news must never be filed as a failure: the point of the filter
    /// is that what it shows is worth looking at.
    #[test]
    fn the_everyday_kinds_are_informational() {
        for kind in [
            ActivityType::AddPackage,
            ActivityType::RemovePackage,
            ActivityType::UpdatePackage,
            ActivityType::ServerStart,
            ActivityType::WorkerEnroll,
            ActivityType::WorkerApprove,
            ActivityType::WorkerRevoke,
        ] {
            assert_eq!(kind.severity(), Severity::Info, "{kind:?}");
        }
    }

    #[test]
    fn severities_round_trip_through_their_slug() {
        for severity in [Severity::Info, Severity::Warning, Severity::Error] {
            assert_eq!(Severity::from_slug(severity.slug()), Some(severity));
        }
        assert_eq!(Severity::from_slug("catastrophe"), None);
    }
}
