//! Entity models, originally generated by sea-orm-codegen and now hand-maintained.

use pacman_mirrors::platforms::Platform;
use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

// todo the toSchema derive should be removed to couple db and api
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, ToSchema)]
#[sea_orm(table_name = "builds")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pkg_id: i32,
    /// This build's number *within its package*, counting from 1.
    ///
    /// The public identity of a build is `<pkgbase>/<number>`; [`Self::id`] is
    /// an internal key that no URL, API response or screen shows.
    pub number: i32,
    pub output: Option<String>,
    pub status: Option<i32>,
    pub start_time: Option<i64>,
    pub end_time: Option<i64>,
    #[schema(value_type = String)]
    pub platform: Platform,
    pub version: String,
    /// Id of the worker that holds the active lease on this build, if any.
    pub worker_id: Option<i32>,
    /// Epoch seconds when the current worker's lease expires. Renewed by
    /// heartbeats; a passed value means the worker went silent.
    pub lease_expires_at: Option<i64>,
    /// Number of times this build has been re-enqueued after a silent worker.
    pub attempt_count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::packages::Entity",
        from = "Column::PkgId",
        to = "super::packages::Column::Id"
    )]
    Packages,
}

impl Related<super::packages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Packages.def()
    }
}
impl ActiveModelBehavior for ActiveModel {}
