//! Entity models, originally generated by sea-orm-codegen and now hand-maintained.

use pacman_mirrors::platforms::Platform;
use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

// todo the toSchema derive should be removed to couple db and api
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, ToSchema)]
#[sea_orm(table_name = "builds")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pkg_id: i32,
    /// This build's number *within its package*, counting from 1.
    ///
    /// The public identity of a build is `<pkgbase>/<number>`; [`Self::id`] is
    /// an internal key that no URL, API response or screen shows.
    pub number: i32,
    pub status: Option<i32>,
    pub start_time: Option<i64>,
    pub end_time: Option<i64>,
    #[schema(value_type = String)]
    pub platform: Platform,
    pub version: String,
    /// Total size in bytes of the artifacts this build produced.
    ///
    /// `None` for a build that produced nothing to measure -- one that failed,
    /// was cancelled, or has not finished -- and for a successful build that
    /// predates the column. Per platform, since a build is: a package's total
    /// is the sum across every platform it builds for.
    pub size: Option<i64>,
    /// High-water mark of the build process tree's memory, in bytes: the
    /// `memory.peak` of the cgroup the build ran in. `None` for a build whose
    /// worker did not report one.
    pub peak_memory: Option<i64>,
    /// Disk the build used on its worker, part by part, as stored; see
    /// `aurcache_common::api::builds::DiskUsage`. `None` where not reported.
    pub disk_chroot: Option<i64>,
    pub disk_workdir: Option<i64>,
    pub disk_sources: Option<i64>,
    pub disk_build_tree: Option<i64>,
    /// Id of the worker that holds the active lease on this build, if any.
    pub worker_id: Option<i32>,
    /// Epoch seconds when the current worker's lease expires. Renewed by
    /// heartbeats; a passed value means the worker went silent.
    pub lease_expires_at: Option<i64>,
    /// Number of times this build has been re-enqueued after a silent worker.
    pub attempt_count: i32,
    /// Why this build row was created: `user`, `auto_update`, or `timeout_retry`
    /// (see `aurcache_common::build_state::BuildTrigger`). The retry budget for
    /// abandoned builds is derived from the consecutive `timeout_retry` run in
    /// this column rather than counted anywhere.
    pub trigger: i32,
    /// Why the server stopped this build, when it did the stopping (`canceled`,
    /// `lease_expired`, `max_duration` — see
    /// `aurcache_common::build_state::EndReason`). `None` for a build whose
    /// terminal outcome the worker reported, whose `CompleteReport.reason` text
    /// is the record.
    pub end_reason: Option<i32>,
    /// What this build's VCS (`git+...`) sources were at, as a JSON object of
    /// `source_url -> commit`.
    ///
    /// The record of what the build was *made from*, as against
    /// [`crate::package_vcs_sources`], which is what the version check last
    /// *saw*. `None` is unknown -- a build that predates this, or one whose
    /// sources could not be resolved -- and never means "nothing changed".
    pub vcs_sources: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::packages::Entity",
        from = "Column::PkgId",
        to = "super::packages::Column::Id"
    )]
    Packages,
    /// The worker that ran this build.
    ///
    /// Joined left, never inner: `worker_id` is null for a build nobody has
    /// claimed yet, and an inner join would silently drop exactly the queued
    /// builds a list is most often consulted about.
    #[sea_orm(
        belongs_to = "super::workers::Entity",
        from = "Column::WorkerId",
        to = "super::workers::Column::Id"
    )]
    Workers,
}

impl Related<super::packages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Packages.def()
    }
}
impl ActiveModelBehavior for ActiveModel {}
