//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Re-exported from `aurcache-types`, where they live so the API and a
/// frontend can share them. They are still this entity's column types.
pub use aurcache_types::source::{GitSourceSpec, SourceData};

// todo the toSchema derive should be removed to couple db and api
#[derive(
    Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Text")]
#[derive(Default)]
pub enum SourceType {
    #[sea_orm(string_value = "aur")]
    #[default]
    Aur,
    #[sea_orm(string_value = "git")]
    Git,
    #[sea_orm(string_value = "upload")]
    Upload,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, ToSchema)]
#[sea_orm(table_name = "packages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    /// Canonical package identifier (this is the pkgbase).
    ///
    /// We track one row per pkgbase, so `name` stores the pkgbase value.
    pub name: String,
    pub status: i32,
    pub out_of_date: i32,
    pub upstream_version: Option<String>,
    pub latest_build: Option<i32>,
    pub build_flags: String,
    pub platforms: String,
    pub source_type: SourceType,
    #[schema(value_type = String)]
    pub source_data: SourceData,
    pub directly_requested: bool,
    pub split_packages: Option<String>,
    pub provides: Option<String>,
    /// Optional multi-file unified diff (similar to a `git diff`) applied to the
    /// fetched source before it is handed to the builder. May touch `PKGBUILD`
    /// or any other tracked source file; `.SRCINFO` is always regenerated from
    /// the (possibly patched) `PKGBUILD` when a patch is present, so it never
    /// needs to be included in the patch itself.
    pub patch: Option<String>,
    // Metadata mirrored from the AUR by the version-check scheduler, so the
    // package route can answer without a live lookup. All nullable: a package
    // that has not been checked since these columns were added has none yet.
    pub aur_description: Option<String>,
    pub aur_maintainer: Option<String>,
    pub aur_project_url: Option<String>,
    /// The AUR reports a list; stored joined with ", " for display.
    pub aur_licenses: Option<String>,
    pub aur_first_submitted: Option<i64>,
    pub aur_last_modified: Option<i64>,
    /// The AUR's own "flagged out of date" marker. Not [`Self::out_of_date`],
    /// which means upstream is newer than what we last built.
    pub aur_flagged_outdated: Option<bool>,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::builds::Entity")]
    Builds,
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
    #[sea_orm(has_many = "super::package_vcs_sources::Entity")]
    PackageVcsSources,
    #[sea_orm(
        belongs_to = "super::builds::Entity",
        from = "Column::LatestBuild",
        to = "super::builds::Column::Id"
    )]
    LatestBuild,
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl Related<super::package_vcs_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PackageVcsSources.def()
    }
}

impl Related<super::builds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Builds.def()
    }
}
