//! Entity models, originally generated by sea-orm-codegen and now hand-maintained.

use crate::lists::{BuildFlags, Platforms};
use aurcache_common::build_state::BuildState;
use sea_orm::entity::prelude::*;

/// Re-exported from `aurcache-common`, where they live so the API and a
/// frontend can share them. They are still this entity's column types.
pub use aurcache_common::source::{GitSourceSpec, SourceData};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "packages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    /// Canonical package identifier (this is the pkgbase).
    ///
    /// We track one row per pkgbase, so `name` stores the pkgbase value.
    pub name: String,
    /// What the package's builds add up to; see
    /// [`refresh_package_status`](crate::helpers::builds::refresh_package_status),
    /// the only thing that writes it once the package has builds.
    pub status: BuildState,
    pub out_of_date: bool,
    pub upstream_version: Option<String>,
    pub build_flags: BuildFlags,
    pub platforms: Platforms,
    pub source_data: SourceData,
    pub directly_requested: bool,
    pub split_packages: Option<String>,
    pub provides: Option<String>,
    /// Optional source patch applied to the fetched source before it is handed
    /// to the builder: `aurcache_utils::patch::SourcePatch` as JSON, one unified
    /// diff per file. May touch `PKGBUILD` or any other tracked source file;
    /// `.SRCINFO` is always regenerated from the (possibly patched) `PKGBUILD`
    /// when a patch is present, so it never needs to be included itself.
    pub patch: Option<String>,
    // Metadata mirrored from the AUR by the version-check scheduler, so the
    // package route can answer without a live lookup. All nullable: a package
    // that has not been checked since these columns were added has none yet.
    pub source_description: Option<String>,
    pub source_maintainer: Option<String>,
    pub source_project_url: Option<String>,
    /// The AUR reports a list; stored joined with ", " for display.
    pub source_licenses: Option<String>,
    pub source_first_submitted: Option<i64>,
    pub source_last_modified: Option<i64>,
    /// The AUR's own "flagged out of date" marker. Not [`Self::out_of_date`],
    /// which means upstream is newer than what we last built.
    pub aur_flagged_outdated: Option<bool>,
    /// Whether the last AUR check did not find this package — it was removed
    /// from the AUR. `None` before the first check.
    ///
    /// Recorded rather than inferred from absent metadata: metadata now comes
    /// from the source checkout, which an unlisted package still has.
    pub aur_missing: Option<bool>,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::builds::Entity")]
    Builds,
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
    #[sea_orm(has_many = "super::package_vcs_sources::Entity")]
    PackageVcsSources,
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl Related<super::package_vcs_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PackageVcsSources.def()
    }
}

impl Related<super::builds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Builds.def()
    }
}
