//! Wire types for the remote-worker protocol (`/api/worker`).
//!
//! These are shared between the backend API and the `aurcache-worker` binary,
//! so their JSON representation is a stable contract. Keep field names stable.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Enrollment request a worker sends on first contact (no client cert yet).
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct RegisterRequest {
    pub name: String,
    pub native_arches: Vec<String>,
    #[serde(default)]
    pub emulated_arches: Vec<String>,
    pub version: String,
    /// PEM-encoded certificate signing request generated by the worker.
    pub csr_pem: String,
    /// Optional shared enrollment token (`AURCACHE_ENROLLMENT_TOKEN` on the
    /// worker). When it matches the server's configured token the worker is
    /// auto-approved without an admin click.
    #[serde(default)]
    pub enrollment_token: Option<String>,
    /// Exact pkgbase names this worker is specially provisioned for
    /// (`WORKER_PACKAGES`). Reserves those packages to workers that name them.
    #[serde(default)]
    pub packages: Vec<String>,
    /// Scheduling preference, higher wins (`WORKER_PRIORITY`).
    #[serde(default)]
    pub priority: i32,
    /// Maximum concurrent builds (`WORKER_CONCURRENCY`), so the server can tell
    /// whether this worker still has capacity.
    #[serde(default = "default_concurrency")]
    pub concurrency: u32,
}

/// A worker that does not report its concurrency is assumed to run one build.
const fn default_concurrency() -> u32 {
    1
}

/// Enrollment status returned while a worker polls for approval.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct RegisterStatus {
    /// Where the worker stands in the approval workflow.
    ///
    /// The same type the column holds and the operator API returns: this used
    /// to be a `String` compared against constants that were defined three
    /// times over, in three crates.
    pub status: crate::api::worker::ApprovalStatus,
    /// PEM of the CA-signed leaf certificate, present once approved.
    pub signed_cert: Option<String>,
    /// PEM of the CA certificate, present once approved (for the worker to pin).
    pub ca_cert: Option<String>,
    /// A `pacman.conf` `[repo]` section for this AURCache instance, with the
    /// host left as the placeholder [`REPO_HOST_PLACEHOLDER`] for the worker
    /// to fill in. Empty when this instance publishes no repository.
    ///
    /// The host cannot be decided server-side: workers reach the same server by
    /// different addresses — a compose service name, a LAN address, `localhost`
    /// for a worker embedded alongside it — and one baked-in value is wrong for
    /// all but one of them. Everything else about the section (its name, the
    /// port, `SigLevel`) stays the server's to choose, so it is sent rendered
    /// except for that one field.
    ///
    /// Sent at registration rather than per job because it describes the
    /// deployment, not the build.
    #[serde(default)]
    pub repo_template: String,
}

/// Placeholder the worker replaces with the host it reaches the server on.
///
/// Chosen so pacman never interprets it: `$` would collide with pacman's own
/// `$arch` / `$repo` substitution.
pub const REPO_HOST_PLACEHOLDER: &str = "%AURCACHE_HOST%";

/// What a worker wants the server to do about this build's mirrorlist.
///
/// The checksum is one the *server* produced and sent alongside a mirrorlist;
/// the worker only echoes it back. Nothing on the worker side computes a
/// digest, so the two ends cannot disagree about the algorithm.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case", tag = "mode")]
pub enum MirrorlistPreference {
    /// The worker has its own mirrorlist and wants none sent.
    Local,
    /// The worker takes the server's, and holds these checksums keyed by
    /// architecture. Keyed because a claim is sent *before* the server picks a
    /// job, so the worker does not yet know which of the arches it builds this
    /// answer will be for. Empty means it holds nothing yet.
    Server {
        #[serde(default)]
        checksums: std::collections::BTreeMap<String, String>,
    },
}

/// A worker that says nothing holds nothing, so it is sent the mirrorlist in
/// full. That is what a worker predating this field does, which is why the
/// default has to be this variant rather than [`MirrorlistPreference::Local`].
impl Default for MirrorlistPreference {
    fn default() -> Self {
        Self::Server {
            checksums: std::collections::BTreeMap::new(),
        }
    }
}

/// A worker's request to claim a job, advertising the arches it can build so
/// the server can route native vs emulated work.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct ClaimRequest {
    pub native_arches: Vec<String>,
    #[serde(default)]
    pub emulated_arches: Vec<String>,
    /// What the worker already holds, so the server can skip resending an
    /// unchanged mirrorlist. Unlike the arch fields this *is* read: it says
    /// something about the caller that only the caller knows.
    #[serde(default)]
    pub mirrorlist: MirrorlistPreference,
}

/// Everything a worker needs to build a package without ever contacting the AUR.
///
/// Sources are downloaded separately (`GET /jobs/{id}/source`); this carries the
/// self-contained build configuration.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct JobDescriptor {
    pub build_id: i32,
    pub pkgbase: String,
    /// Target architecture, e.g. `x86_64`, `aarch64`.
    pub arch: String,
    #[serde(default)]
    pub build_flags: Vec<String>,
    /// Rendered `makepkg.conf` for the build.
    pub makepkg_conf: String,
    /// Rendered `pacman.conf` for the build.
    pub pacman_conf: String,
    /// Per-arch mirrorlist content when the server has one for this arch and
    /// the worker does not already hold it. `None` together with
    /// `mirrorlist_unchanged == false` means the server has none, and the
    /// worker falls back to its image's built-in mirrorlist.
    pub mirrorlist: Option<String>,
    /// Checksum of the `mirrorlist` sent above, for the worker to echo back on
    /// its next claim. Absent whenever no content was sent.
    #[serde(default)]
    pub mirrorlist_checksum: Option<String>,
    /// The server has a mirrorlist for this arch and it matches the checksum
    /// the worker sent, so the content was omitted; keep using what you have.
    ///
    /// Only ever true in response to a claim that carried a checksum, so a
    /// worker predating this field never sees it and keeps receiving the
    /// content in full.
    #[serde(default)]
    pub mirrorlist_unchanged: bool,
    /// `validpgpkeys` the worker must trust before building.
    #[serde(default)]
    pub pgp_keys: Vec<String>,
}

/// Periodic liveness signal. Carries the set of builds the worker is actively
/// running so the server can renew their leases and requeue any it dropped.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct Heartbeat {
    pub active_build_ids: Vec<i32>,
    pub version: String,
}

/// Terminal report for a single build.
///
/// A report with `success == false` (including OOM / non-zero exit) is a
/// deterministic failure and marks the build FAILED without re-enqueue.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct CompleteReport {
    pub success: bool,
    /// Exit code of the build process (e.g. 137 for an OOM kill), when known.
    pub exit_code: Option<i32>,
    /// Human-readable failure reason.
    pub reason: Option<String>,
    /// True when the build stopped because it was canceled.
    #[serde(default)]
    pub canceled: bool,
}

/// Worker's poll response for cancel on a specific job.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct JobStatus {
    pub cancel_requested: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn round_trip<T>(value: &T) -> T
    where
        T: Serialize + for<'de> Deserialize<'de>,
    {
        let json = serde_json::to_string(value).expect("serialize");
        serde_json::from_str(&json).expect("deserialize")
    }

    #[test]
    fn job_descriptor_round_trips() {
        let job = JobDescriptor {
            build_id: 42,
            pkgbase: "hello".into(),
            arch: "x86_64".into(),
            build_flags: vec!["--nocheck".into()],
            makepkg_conf: "PACKAGER=x".into(),
            pacman_conf: "[repo]".into(),
            mirrorlist: Some("Server = https://example/\\$repo".into()),
            mirrorlist_checksum: Some("abc123".into()),
            mirrorlist_unchanged: false,
            pgp_keys: vec!["ABCDEF".into()],
        };
        let back = round_trip(&job);
        assert_eq!(job.build_id, back.build_id);
        assert_eq!(job.pgp_keys, back.pgp_keys);
        assert_eq!(job.mirrorlist, back.mirrorlist);
        assert_eq!(job.mirrorlist_checksum, back.mirrorlist_checksum);
    }

    /// A worker predating the mirrorlist fields sends no `mirrorlist` on its
    /// claim. That has to read as "I hold nothing", so the server keeps sending
    /// the content in full and the old worker behaves exactly as before.
    #[test]
    fn a_claim_without_a_mirrorlist_preference_holds_nothing() {
        let old = r#"{"native_arches":["x86_64"],"emulated_arches":[]}"#;
        let claim: ClaimRequest = serde_json::from_str(old).expect("deserialize old claim");
        assert_eq!(claim.mirrorlist, MirrorlistPreference::default());
        assert_eq!(
            claim.mirrorlist,
            MirrorlistPreference::Server {
                checksums: std::collections::BTreeMap::new()
            }
        );
    }

    /// Conversely, a job descriptor from a server predating those fields still
    /// deserializes: the worker sees content with no checksum and simply uses
    /// it without caching.
    #[test]
    fn a_job_descriptor_without_the_new_fields_deserializes() {
        let old = r#"{"build_id":1,"pkgbase":"hello","arch":"x86_64","build_flags":[],
            "makepkg_conf":"","pacman_conf":"","mirrorlist":"Server = a\n","pgp_keys":[]}"#;
        let job: JobDescriptor = serde_json::from_str(old).expect("deserialize old descriptor");
        assert_eq!(job.mirrorlist.as_deref(), Some("Server = a\n"));
        assert!(job.mirrorlist_checksum.is_none());
        assert!(!job.mirrorlist_unchanged);
    }

    /// The preference is tagged, so adding a variant later does not silently
    /// deserialize as an existing one.
    #[test]
    fn mirrorlist_preference_round_trips() {
        assert_eq!(
            round_trip(&MirrorlistPreference::Local),
            MirrorlistPreference::Local
        );
        let mut checksums = std::collections::BTreeMap::new();
        checksums.insert("x86_64".to_string(), "abc".to_string());
        let held = MirrorlistPreference::Server { checksums };
        assert_eq!(round_trip(&held), held);
    }

    #[test]
    fn heartbeat_round_trips() {
        let hb = Heartbeat {
            active_build_ids: vec![1, 2, 3],
            version: "0.1.0".into(),
        };
        assert_eq!(round_trip(&hb).active_build_ids, hb.active_build_ids);
    }

    #[test]
    fn complete_report_defaults_canceled_false() {
        let parsed: CompleteReport =
            serde_json::from_str(r#"{"success":false,"exit_code":137}"#).expect("parse");
        assert!(!parsed.success);
        assert_eq!(parsed.exit_code, Some(137));
        assert!(!parsed.canceled);
    }

    #[test]
    fn claim_request_emulated_defaults_empty() {
        let parsed: ClaimRequest =
            serde_json::from_str(r#"{"native_arches":["x86_64"]}"#).expect("parse");
        assert_eq!(parsed.native_arches, vec!["x86_64".to_string()]);
        assert!(parsed.emulated_arches.is_empty());
    }
}
