//! Wire types for the remote-worker protocol (`/api/worker`).
//!
//! These are shared between the backend API and the `aurcache-worker` binary,
//! so their JSON representation is a stable contract. Keep field names stable.

use crate::worker_config::{ConfigSnapshot, EffectiveConfig, SettingDecl};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use utoipa::ToSchema;

/// Enrollment request a worker sends on first contact (no client cert yet).
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct RegisterRequest {
    pub name: String,
    pub native_arches: Vec<String>,
    #[serde(default)]
    pub emulated_arches: Vec<String>,
    pub version: String,
    /// Which build strategy this worker runs -- `chroot`, `docker`. Free-form
    /// so a future executor can name itself without the server knowing about it
    /// in advance; the server stores and shows whatever arrives.
    ///
    /// Empty from a worker predating the field, which the Workers page shows as
    /// unknown rather than guessing.
    #[serde(default)]
    pub kind: String,
    /// PEM-encoded certificate signing request generated by the worker.
    pub csr_pem: String,
    /// Optional shared enrollment token (`AURCACHE_ENROLLMENT_TOKEN` on the
    /// worker). When it matches the server's configured token the worker is
    /// auto-approved without an admin click.
    #[serde(default)]
    pub enrollment_token: Option<String>,
    /// Exact pkgbase names this worker is specially provisioned for
    /// (`WORKER_PACKAGES`). Reserves those packages to workers that name them.
    #[serde(default)]
    pub packages: Vec<String>,
    /// Scheduling preference, higher wins (`WORKER_PRIORITY`).
    #[serde(default)]
    pub priority: i32,
    /// Maximum concurrent builds (`WORKER_CONCURRENCY`), so the server can tell
    /// whether this worker still has capacity.
    #[serde(default = "default_concurrency")]
    pub concurrency: u32,
    /// The settings this worker accepts, compiled into it.
    ///
    /// Sent at every registration, because a worker's environment is the source
    /// of truth for what its defaults currently are. `None` from a worker that
    /// predates this, which the Workers page shows as "configuration not
    /// reported by this worker version" rather than as a worker with no
    /// settings.
    #[serde(default)]
    pub settings: Option<Vec<SettingDecl>>,
}

/// A worker that does not report its concurrency is assumed to run one build.
const fn default_concurrency() -> u32 {
    1
}

/// Enrollment status returned while a worker polls for approval.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct RegisterStatus {
    /// Where the worker stands in the approval workflow.
    ///
    /// The same type the column holds and the operator API returns: this used
    /// to be a `String` compared against constants that were defined three
    /// times over, in three crates.
    pub status: crate::api::worker::ApprovalStatus,
    /// PEM of the CA-signed leaf certificate, present once approved.
    pub signed_cert: Option<String>,
    /// PEM of the CA certificate, present once approved (for the worker to pin).
    pub ca_cert: Option<String>,
    /// A `pacman.conf` `[repo]` section for this AURCache instance, with the
    /// host left as the placeholder [`REPO_HOST_PLACEHOLDER`] for the worker
    /// to fill in. Empty when this instance publishes no repository.
    ///
    /// The host cannot be decided server-side: workers reach the same server by
    /// different addresses — a compose service name, a LAN address, `localhost`
    /// for a worker embedded alongside it — and one baked-in value is wrong for
    /// all but one of them. Everything else about the section (its name, the
    /// port, `SigLevel`) stays the server's to choose, so it is sent rendered
    /// except for that one field.
    ///
    /// Sent at registration rather than per job because it describes the
    /// deployment, not the build.
    #[serde(default)]
    pub repo_template: String,
}

/// Placeholder the worker replaces with the host it reaches the server on.
///
/// Chosen so pacman never interprets it: `$` would collide with pacman's own
/// `$arch` / `$repo` substitution.
pub const REPO_HOST_PLACEHOLDER: &str = "%AURCACHE_HOST%";

/// What a worker wants the server to do about this build's mirrorlist.
///
/// The checksum is one the *server* produced and sent alongside a mirrorlist;
/// the worker only echoes it back. Nothing on the worker side computes a
/// digest, so the two ends cannot disagree about the algorithm.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case", tag = "mode")]
pub enum MirrorlistPreference {
    /// The worker has its own mirrorlist and wants none sent.
    Local,
    /// The worker takes the server's, and holds these checksums keyed by
    /// architecture. Keyed because a claim is sent *before* the server picks a
    /// job, so the worker does not yet know which of the arches it builds this
    /// answer will be for. Empty means it holds nothing yet.
    Server {
        #[serde(default)]
        checksums: std::collections::BTreeMap<String, String>,
    },
}

/// A worker that says nothing holds nothing, so it is sent the mirrorlist in
/// full. That is what a worker predating this field does, which is why the
/// default has to be this variant rather than [`MirrorlistPreference::Local`].
impl Default for MirrorlistPreference {
    fn default() -> Self {
        Self::Server {
            checksums: std::collections::BTreeMap::new(),
        }
    }
}

/// A worker's request to claim a job, advertising the arches it can build so
/// the server can route native vs emulated work.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct ClaimRequest {
    pub native_arches: Vec<String>,
    #[serde(default)]
    pub emulated_arches: Vec<String>,
    /// What the worker already holds, so the server can skip resending an
    /// unchanged mirrorlist. Unlike the arch fields this *is* read: it says
    /// something about the caller that only the caller knows.
    #[serde(default)]
    pub mirrorlist: MirrorlistPreference,
}

/// Everything a worker needs to build a package without ever contacting the AUR.
///
/// Sources are downloaded separately (`GET /jobs/{id}/source`); this carries the
/// self-contained build configuration.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct JobDescriptor {
    pub build_id: i32,
    pub pkgbase: String,
    /// Target architecture, e.g. `x86_64`, `aarch64`.
    pub arch: String,
    #[serde(default)]
    pub build_flags: Vec<String>,
    /// Keep the build tree between builds rather than starting from an empty
    /// one. Resolved server-side from the package's settings, because only the
    /// server knows them; the worker decides where such a tree lives.
    #[serde(default)]
    pub persistent_builddir: bool,
    /// Rendered `makepkg.conf` for the build.
    pub makepkg_conf: String,
    /// Rendered `pacman.conf` for the build.
    pub pacman_conf: String,
    /// Per-arch mirrorlist content when the server has one for this arch and
    /// the worker does not already hold it. `None` together with
    /// `mirrorlist_unchanged == false` means the server has none, and the
    /// worker falls back to its image's built-in mirrorlist.
    pub mirrorlist: Option<String>,
    /// Checksum of the `mirrorlist` sent above, for the worker to echo back on
    /// its next claim. Absent whenever no content was sent.
    #[serde(default)]
    pub mirrorlist_checksum: Option<String>,
    /// The server has a mirrorlist for this arch and it matches the checksum
    /// the worker sent, so the content was omitted; keep using what you have.
    ///
    /// Only ever true in response to a claim that carried a checksum, so a
    /// worker predating this field never sees it and keeps receiving the
    /// content in full.
    #[serde(default)]
    pub mirrorlist_unchanged: bool,
    /// `validpgpkeys` the worker must trust before building.
    #[serde(default)]
    pub pgp_keys: Vec<String>,
    /// The `git+` sources whose commit the worker should report back, so the
    /// server learns what the build was *actually* made from rather than what
    /// it guessed when it queued it.
    ///
    /// Sent by the server rather than worked out on the worker because the
    /// directory a source lands in follows makepkg's naming rule, and two
    /// implementations of that rule drifting apart would key a commit to a
    /// `source_url` nobody compares against -- silently.
    #[serde(default)]
    pub vcs_sources: Vec<JobVcsSource>,
    /// Package names this build is expected to produce: the pkgbase plus any
    /// split-package names recorded for it.
    ///
    /// Empty from a server predating the field, which means "just the
    /// pkgbase".
    #[serde(default)]
    pub packages: Vec<String>,
    /// Full version (`pkgver-pkgrel`) the produced archives must carry in
    /// their filenames. Empty from a server predating the field.
    #[serde(default)]
    pub version: String,
}

/// One `git+` source of a build, as the worker needs to find it.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema, PartialEq, Eq)]
pub struct JobVcsSource {
    /// The raw `.SRCINFO` source string, which is the key the server records
    /// the answer under.
    pub source_url: String,
    /// The directory makepkg clones it into, relative to `SRCDEST`.
    pub dir: String,
    /// The ref makepkg checks out: a branch or tag name, or `HEAD`.
    pub git_ref: String,
}

/// Periodic liveness signal. Carries the set of builds the worker is actively
/// running so the server can renew their leases and requeue any it dropped.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct Heartbeat {
    pub active_build_ids: Vec<i32>,
    pub version: String,
    /// What each declared setting resolved to, sent when it differs from what
    /// this worker last got the server to store: once per worker process, and
    /// again after each delivery of new values.
    ///
    /// Rides the heartbeat rather than registration so a value that changes
    /// without re-registering still reaches the server.
    #[serde(default)]
    pub effective: Option<EffectiveConfig>,
    /// The revision of the last [`ConfigSnapshot`] this worker took, sent on
    /// every heartbeat so the server can tell whether it holds the current one.
    ///
    /// Separate from `effective` on purpose. Receiving a snapshot and running
    /// its values are different things -- a value pinned on the machine is
    /// received and deliberately not run -- and a single "applied" marker
    /// would make the server resend such a snapshot for ever.
    #[serde(default)]
    pub received_revision: Option<String>,
}

/// The server's answer to a heartbeat.
///
/// Carried by the same request the worker already sends every few seconds, so
/// it is the one channel back the pull-only worker has. A non-empty `cancel` is
/// the server saying "these builds are no longer ACTIVE under you — stop
/// them"; the worker aborts them on its next 5 s tick.
#[derive(Clone, Debug, Default, Serialize, Deserialize, ToSchema)]
pub struct HeartbeatResponse {
    /// Build ids this worker should stop running.
    #[serde(default)]
    pub cancel: Vec<i32>,
    /// The values set for this worker on the server, when the worker does not
    /// hold them yet.
    ///
    /// Only ever sent to a worker that declared its settings: an older worker
    /// could not use it. Optional with a default, because a worker reads an
    /// answer it cannot parse as an empty one, which would also drop `cancel`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config: Option<ConfigSnapshot>,
}

/// Terminal report for a single build.
///
/// A report with `success == false` (including OOM / non-zero exit) is a
/// deterministic failure and marks the build FAILED without re-enqueue.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct CompleteReport {
    pub success: bool,
    /// Exit code of the build process (e.g. 137 for an OOM kill), when known.
    pub exit_code: Option<i32>,
    /// Human-readable failure reason.
    pub reason: Option<String>,
    /// True when the build stopped because it was canceled.
    #[serde(default)]
    pub canceled: bool,
    /// High-water mark of the build process tree's memory, in bytes.
    ///
    /// `None` when the worker could not measure it -- an old worker, a build
    /// that ended before the first sample, or a `/proc` it could not read.
    /// Distinct from a build that genuinely used nothing, which cannot happen.
    #[serde(default)]
    pub peak_memory_bytes: Option<i64>,
    /// What each `git+` source was at in the worker's own source cache when the
    /// build finished, keyed by `source_url`.
    ///
    /// Empty from a worker that predates this, or for a source it could not
    /// resolve; the server keeps the commit it recorded at queue time in that
    /// case, which is the older of the two and so errs toward a redundant
    /// rebuild rather than a missed one.
    #[serde(default)]
    pub vcs_commits: BTreeMap<String, String>,
}

/// Worker's poll response for cancel on a specific job.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct JobStatus {
    pub cancel_requested: bool,
}

/// A problem the worker noticed on its own account, sent best-effort alongside
/// whatever it already wrote to its own journal.
///
/// Free text rather than a kind of its own: the worker's call sites are not a
/// catalogue the server can be expected to keep in step with release for
/// release, so the server files every one under one of two kinds
/// (`worker.warning`, `worker.error`) and keeps this as the sentence.
#[derive(Clone, Debug, Serialize, Deserialize, ToSchema)]
pub struct WorkerLogReport {
    pub severity: crate::api::activity::Severity,
    /// The build this happened during, when there is one -- absent for
    /// something that is not about any single job, such as chroot or cache
    /// maintenance.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub build_id: Option<i32>,
    pub message: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn round_trip<T>(value: &T) -> T
    where
        T: Serialize + for<'de> Deserialize<'de>,
    {
        let json = serde_json::to_string(value).expect("serialize");
        serde_json::from_str(&json).expect("deserialize")
    }

    #[test]
    fn job_descriptor_round_trips() {
        let job = JobDescriptor {
            build_id: 42,
            persistent_builddir: false,
            pkgbase: "hello".into(),
            arch: "x86_64".into(),
            build_flags: vec!["--nocheck".into()],
            makepkg_conf: "PACKAGER=x".into(),
            pacman_conf: "[repo]".into(),
            mirrorlist: Some("Server = https://example/\\$repo".into()),
            mirrorlist_checksum: Some("abc123".into()),
            mirrorlist_unchanged: false,
            packages: vec!["hello".into(), "hello-docs".into()],
            version: "1.0-1".into(),
            pgp_keys: vec!["ABCDEF".into()],
            vcs_sources: vec![JobVcsSource {
                source_url: "git+https://example.test/repo.git".into(),
                dir: "repo".into(),
                git_ref: "HEAD".into(),
            }],
        };
        let back = round_trip(&job);
        assert_eq!(job.build_id, back.build_id);
        assert_eq!(job.vcs_sources, back.vcs_sources);
        assert_eq!(job.pgp_keys, back.pgp_keys);
        assert_eq!(job.mirrorlist, back.mirrorlist);
        assert_eq!(job.mirrorlist_checksum, back.mirrorlist_checksum);
        assert_eq!(job.packages, back.packages);
        assert_eq!(job.version, back.version);
    }

    /// A worker predating the kind field sends none, which must deserialize
    /// rather than rejecting the registration outright.
    #[test]
    fn a_registration_without_a_kind_deserializes() {
        let old = r#"{"name":"w","native_arches":["x86_64"],"version":"0.1.0","csr_pem":"x"}"#;
        let req: RegisterRequest = serde_json::from_str(old).expect("deserialize old registration");
        assert!(
            req.kind.is_empty(),
            "an unreported kind must not be guessed"
        );
    }

    /// A worker predating the mirrorlist fields sends no `mirrorlist` on its
    /// claim. That has to read as "I hold nothing", so the server keeps sending
    /// the content in full and the old worker behaves exactly as before.
    #[test]
    fn a_claim_without_a_mirrorlist_preference_holds_nothing() {
        let old = r#"{"native_arches":["x86_64"],"emulated_arches":[]}"#;
        let claim: ClaimRequest = serde_json::from_str(old).expect("deserialize old claim");
        assert_eq!(claim.mirrorlist, MirrorlistPreference::default());
        assert_eq!(
            claim.mirrorlist,
            MirrorlistPreference::Server {
                checksums: std::collections::BTreeMap::new()
            }
        );
    }

    /// Conversely, a job descriptor from a server predating those fields still
    /// deserializes: the worker sees content with no checksum and simply uses
    /// it without caching.
    #[test]
    fn a_job_descriptor_without_the_new_fields_deserializes() {
        let old = r#"{"build_id":1,"pkgbase":"hello","arch":"x86_64","build_flags":[],
            "makepkg_conf":"","pacman_conf":"","mirrorlist":"Server = a\n","pgp_keys":[]}"#;
        let job: JobDescriptor = serde_json::from_str(old).expect("deserialize old descriptor");
        assert_eq!(job.mirrorlist.as_deref(), Some("Server = a\n"));
        assert!(job.mirrorlist_checksum.is_none());
        assert!(!job.mirrorlist_unchanged);
    }

    /// The preference is tagged, so adding a variant later does not silently
    /// deserialize as an existing one.
    #[test]
    fn mirrorlist_preference_round_trips() {
        assert_eq!(
            round_trip(&MirrorlistPreference::Local),
            MirrorlistPreference::Local
        );
        let mut checksums = std::collections::BTreeMap::new();
        checksums.insert("x86_64".to_string(), "abc".to_string());
        let held = MirrorlistPreference::Server { checksums };
        assert_eq!(round_trip(&held), held);
    }

    #[test]
    fn heartbeat_round_trips() {
        let hb = Heartbeat {
            active_build_ids: vec![1, 2, 3],
            version: "0.1.0".into(),
            effective: None,
            received_revision: Some("abc".into()),
        };
        let back = round_trip(&hb);
        assert_eq!(back.active_build_ids, hb.active_build_ids);
        assert_eq!(back.received_revision, hb.received_revision);
    }

    /// A worker that predates the configuration report sends neither field, and
    /// both ends have to keep working: the server reads a heartbeat without
    /// `effective`, and a worker reads a registration it did not declare
    /// settings in.
    #[test]
    fn the_configuration_fields_are_optional_on_the_wire() {
        let hb: Heartbeat =
            serde_json::from_str(r#"{"active_build_ids":[],"version":"0.1.0"}"#).expect("parse");
        assert!(hb.effective.is_none());
        assert!(hb.received_revision.is_none());
    }

    /// An empty cancel list must deserialize — a server that has nothing to
    /// stop says so in full, and the field has to be optional for callers that
    /// predate it.
    #[test]
    fn an_empty_cancel_list_deserializes() {
        let parsed: HeartbeatResponse = serde_json::from_str(r#"{"cancel":[]}"#).expect("parse");
        assert!(parsed.cancel.is_empty());
        assert!(parsed.config.is_none());
        let bare: HeartbeatResponse = serde_json::from_str(r#"{}"#).expect("parse");
        assert!(bare.cancel.is_empty());
    }

    /// A worker predating snapshots must still read `cancel` from an answer
    /// that carries one -- losing the abort list to an unknown field would be
    /// a Stop that silently never arrives. The server does not send it to such
    /// a worker, but the answer must not depend on that alone.
    #[test]
    fn a_snapshot_does_not_cost_an_older_reader_its_cancel_list() {
        #[derive(Deserialize)]
        struct OlderResponse {
            cancel: Vec<i32>,
        }
        let answer = HeartbeatResponse {
            cancel: vec![7],
            config: Some(ConfigSnapshot {
                revision: "r".into(),
                settings: BTreeMap::from([("concurrency".to_string(), "3".to_string())]),
            }),
        };
        let json = serde_json::to_string(&answer).expect("serialize");
        let older: OlderResponse = serde_json::from_str(&json).expect("an older worker reads it");
        assert_eq!(older.cancel, [7]);
        assert_eq!(round_trip(&answer).config, answer.config);
    }

    #[test]
    fn complete_report_defaults_canceled_false() {
        let parsed: CompleteReport =
            serde_json::from_str(r#"{"success":false,"exit_code":137}"#).expect("parse");
        assert!(!parsed.success);
        assert_eq!(parsed.exit_code, Some(137));
        assert!(!parsed.canceled);
    }

    #[test]
    fn claim_request_emulated_defaults_empty() {
        let parsed: ClaimRequest =
            serde_json::from_str(r#"{"native_arches":["x86_64"]}"#).expect("parse");
        assert_eq!(parsed.native_arches, vec!["x86_64".to_string()]);
        assert!(parsed.emulated_arches.is_empty());
    }
}
